- README.md
* Documentation on how to use KP
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/2)
> docs: add readme docs

- examples/simple/go.mod
- examples/simple/go.sum
- examples/simple_backoff/go.mod
- examples/simple_backoff/go.sum
- go.mod
- go.sum
- kp.go
* Add logging to show which topics are being used. Enables for easier debugging
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/7)
> fix: log topics that are used

- kp.go
* Update logging text (topic -> topics)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/8)
> fix: update logging

- README.md
* Add documentation on how the topics for KP work and how they are generated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/9)
> docs: Update readme. A note on topics

- .github/workflows/build.yaml
- consumer.go
- examples/simple/go.mod
- examples/simple/go.sum
- examples/simple/main.go
- examples/simple_backoff/go.mod
- examples/simple_backoff/go.sum
- examples/simple_backoff/main.go
- go.mod
- go.sum
* Remove logging of potential PII data when using this library by removing log for claimed messages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/13)
> fix: remove logging of claimed message

- kp.go
* fix consumer group name
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/14)
> fix: add suffix to consumer group name

- consumer.go
- consumer_test.go
- examples/simple/main.go
- go.mod
- go.sum
- interface.go
- kp.go
- kp_test.go
* return the error from the function.
* add unit test.
* this PR will not try to catch the error, since we will have V2 in the future and Nish would like to avoid the channel implementation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/15)
> fix: remove logging and update unit test

- kp_test.go
- mocks/mock_kpprocessor.go
- v2/interface.go
- v2/internal/consumer/consumer_test.go
- v2/internal/retrycounter/counter.go
- v2/internal/retrycounter/counter_test.go
- v2/kp.go
- v2/kp_test.go
- v2/producer/producer.go
* Add KPv2 API
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/18)
> feat: add kp v2 API

- examples/simple_backoff/main.go
- v2/interface.go
- v2/internal/middleware/middleware.go
- v2/internal/middleware/middleware_test.go
- v2/kp.go
- v2/kp_example_test.go
- v2/kp_test.go
* This will allow us to write middlewares for anything, like automatic measurements, tracing, maybe even backoff etc.
* This also will allow library users to access raw kafka message to get things like retry count, trace id etc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/19)
> feat: add middleware support

- .github/workflows/deploy-docs.yaml
- docs/docs/contributing/_category_.json
- docs/docs/examples/_category_.json
- docs/docs/examples/end-to-end.md
- docs/docs/examples/producer-raw.md
- docs/docs/features/producer.md
- docs/docs/introduction/configuration.md
- docs/docs/introduction/getting-started.md
- docs/docs/introduction/why-use-kp.md
- docs/docs/middlewares/tracing.md
- docs/docusaurus.config.js
* add documentation for producer, and examples
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/26)
> docs: add more docs

- .github/workflows/deploy-docs.yaml
- v2/interface.go
- v2/internal/middleware/final_middleware.go
- v2/internal/middleware/middleware.go
- v2/kp.go
* refactors some code
* exports a type
* fixes ci deployment
* renames a method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/28)
> ci: fix docs deployment

- .github/workflows/deploy-docs.yaml
- docs/docs/introduction/concepts.md
- docs/docs/introduction/schema-registry.md
- docs/docusaurus.config.js
- v2/internal/consumer/consumer.go
This PR makes the following changes:
* it attempts to fix automatic deployment
* adds kafka core-concepts page
* adds schema-registry page
* attempts to address github trailing slash configuration option warning from docusaurus
* disables autocommits from consumer implementation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/29)
> docs: add documentation on concepts and schema-registry

- docs/docs/contributing/contributing.md
- docs/docs/examples/end-to-end.md
- docs/docs/examples/producer-raw.md
- docs/docs/features/deadletters.md
- docs/docs/features/producer.md
- docs/docs/features/retries.md
- docs/docs/introduction/concepts.md
- docs/docs/introduction/configuration.md
- docs/docs/introduction/getting-started.md
- docs/docs/introduction/schema-registry.md
- docs/docs/introduction/why-use-kp.md
- docs/docs/middlewares/backoff.md
- docs/docs/middlewares/custom-middleware.md
- docs/docs/middlewares/introduction.md
- docs/docs/middlewares/measurements.md
- docs/docs/middlewares/retrycounter.md
- docs/docs/middlewares/tracing.md
- docs/package-lock.json
- docs/src/css/custom.css
* proofread with russel till backoff page, will send another PR for the rest.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/33)
> docs: update documentation

- docs/docs/introduction/why-use-kp.md
- docs/docs/middlewares/backoff.md
- docs/docs/middlewares/custom-middleware.md
- docs/docs/middlewares/introduction.md
- docs/docs/middlewares/metrics.md
- docs/docs/middlewares/retrycounter.md
- docs/docs/middlewares/tracing.md
- v2/kp_example_test.go
- v2/middlewares/backoff/backoff.go
- v2/middlewares/backoff/backoff_test.go
- v2/middlewares/measurement/measurement.go
- v2/middlewares/measurement/measurement_test.go
- v2/middlewares/retry_count/retry_count.go
- v2/middlewares/retry_count/retry_count_test.go
- v2/middlewares/tracing/tracing.go
- v2/middlewares/tracing/tracing_test.go
* This moves all middlewares to their respective packages and renames the handlers.
* Updates the documentation accordingly.
closes #37 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/44)
> refactor: move middlewares to their own respective packages

- docs/docs/introduction/getting-started.md
- docs/docs/introduction/why-use-kp.md
- docs/docs/middlewares/introduction.md
- docs/docs/middlewares/tracing.md
- v2/middlewares/tracing/tracing.go
- v2/middlewares/tracing/tracing_test.go
* This PR closes #43 
* This ensures tracing middleware can't be initialized without a tracer provider.
closes #43
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/49)
> refactor: accept tracer provider on tracing middleware

- docs/docs/middlewares/custom-middleware.md
- v2/middlewares/backoff/backoff.go
- v2/middlewares/interface.go
- v2/middlewares/measurement/measurement.go
- v2/middlewares/retry_count/retry_count.go
- v2/middlewares/tracing/tracing.go
closes #38 
* This adds Middleware to the kp package instead of having to access internal middlewares.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/50)
> refactor: add a KPMiddleware interface

- v2/interface.go
- v2/internal/consumer/consumer.go
- v2/kafkaheaders/set_test.go
- v2/kp.go
- v2/kp_example_test.go
- v2/kp_test.go
- v2/middlewares/consumer/consumer.go
- v2/middlewares/consumer/consumer_test.go
- v2/middlewares/deadletter/deadletter.go
- v2/middlewares/deadletter/deadletter_test.go
- v2/middlewares/interface.go
- v2/middlewares/retry/retry.go
- v2/middlewares/retry/retry_test.go
closes #40 
closes #41 
closes #42 
* This PR converts everything to middleware (consumer, deadletters, and retries).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/52)
> feat: convert everything to middleware

- CODE_OF_CONDUCT.md
* Adds a code of conduct as recommended by github
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/56)
> docs: add code of conduct file

- SECURITY.md
- docs/docusaurus.config.js
* add algolia integration
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/58)
> docs: add algolia integration

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- SECURITY.md
- docs/docusaurus.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/61)
> docs: add issue and pr templates

- .github/workflows/build.yaml
- docs/package-lock.json
I forgot to update the package integrity after upgraded the version, this error wasn't captured since we didn't check it in the CI workflow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/65)
> fix: Update the package integrity

- docs/docs/migration/_category_.json
- docs/docs/migration/migration.md
* add  a migration guide.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/66)
> docs: add a migration guide

- docs/docs/migration/migration.md
* add suggested changes from @jai
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/67)
> docs: update migration guide

- v2/producer/producer.go
- v2/producer/types.go
- v2/producer/untyped.go
fixes #72 
adds an untyped producer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/73)
> feat: add untyped producer

- .github/workflows/build.yaml
- docs/docs/middlewares/metrics.md
- v2/middlewares/measurement/promauto/measurement.go
- v2/middlewares/measurement/promauto/measurement_test.go
- v2/middlewares/measurement/pushgateway/measurement.go
- v2/middlewares/measurement/pushgateway/measurement_test.go
* update documentation in a separate PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/83)
> feat: promauto and pushgateway measurement middlewares

- .github/workflows/shiftleft-go.yaml
- .pre-commit-config.yaml
- Makefile
- mocks/mock_kafkaprocessor.go
- mocks/mock_kpprocessor.go
- v2/config/config.go
* Support ClientID and Debug Parameters
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/85)
> feat: Support ClientID and Debug parameters

- docs/docs/middlewares/backoff.md
- docs/docs/middlewares/consumer.md
- docs/docs/middlewares/custom-middleware.md
- docs/docs/middlewares/deadletter.md
- docs/docs/middlewares/graceful-shutdown.md
- docs/docs/middlewares/metrics.md
- docs/docs/middlewares/order-of-middleware.md
- docs/docs/middlewares/retry.md
- docs/docs/middlewares/retrycounter.md
- docs/docs/middlewares/tracing.md
* This PR adds a documentation page after introduction that highlights the order of execution.
closes #101
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/102)
> docs: document order of execution of middlewares

- .github/workflows/build.yaml
- v2/config/config.go
To support larger size of the message being produce, we are adding the support to increase the limit of the producer in this PR
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/kp/107)
> feat: Add ability to config the max request size to support larger requests[MLOPS-6669]

- .golangci.json
- .pre-commit-config.yaml
- v2/kp_test.go
- v2/middlewares/deadletter/deadletter_test.go
- v2/middlewares/retry/retry_test.go
- v2/producer/producer.go
- v2/producer/types.go
- v2/producer/untyped.go
* Expose events channel for producer to be able to track message delivery events.
> feat: expose producer events channel [SPE-4814]

- .github/workflows/build.yaml
- docs/package-lock.json
* merge all dependabot branches into 1 PR so we can merge in 1 go.
closes #119 
closes #116 
closes #113 
closes #109 
closes #80 
closes #76
> chore: upgrade dependencies

- .github/workflows/build.yaml
* looks like semantic-release is failing because it can't create a new tag/release. This should fix it, but let's see.
> ci: allow ci to also write instead of just read

- .github/workflows/build.yaml
- .golangci.json
- docs/package-lock.json
- go.mod
- go.sum
- v2/go.mod
* merging 2 branch into this one so that I can merge whole thing at once
closes #131 
closes #117
> chore(deps): update dependencies

- docs/docusaurus.config.js
- docs/package-lock.json
- docs/package.json
* this updates docusaurus to new version
> chore(deps): upgrade to latest version of docusaurus
